AWSTemplateFormatVersion: '2010-09-09'
Description: Gaming Club Application Stack

Parameters:
  TableName:
    Type: String
    Default: GamingClubTable
    Description: Name of the DynamoDB table for bookings.

Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST

  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: GamingClubBookingHandler
      Handler: index.handler
      Runtime: nodejs18.x
      Code:
        S3Bucket: !Ref CodeBucket
        S3Key: lambda/gaming-club-handler.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref TableName
      Role: !GetAtt LambdaExecutionRole.Arn

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: LambdaExecutionPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:*
                  - logs:*
                Resource: '*'
